name: synelia-cloud-backend

services:
  blesta:
    build:
      context: ./blesta
      dockerfile: Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?Missing MARIADB_ROOT_PASSWORD}
      MARIADB_BLESTA_PASSWORD: ${MARIADB_BLESTA_PASSWORD:?Missing MARIADB_BLESTA_PASSWORD}
      BLESTA_DOMAIN: ${BLESTA_DOMAIN:-}
      BLESTA_ADMIN_PASSWORD: ${BLESTA_ADMIN_PASSWORD:-}
      FORCE_REINSTALL: ${FORCE_REINSTALL:-0}
    networks:
      - dokploy-network
    volumes:
      - blesta-data:/opt/blesta/data
    depends_on:
      - mariadb

  mariadb:
    image: docker.io/library/mariadb:11
    environment:
      MARIADB_DATABASE: blesta
      MARIADB_USER: blesta
      MARIADB_PASSWORD: ${MARIADB_BLESTA_PASSWORD:?Missing MARIADB_BLESTA_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:?Missing MARIADB_ROOT_PASSWORD}
    networks:
      - dokploy-network
    volumes:
      - mariadb-data:/var/lib/mysql

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    environment:
      PORT: 4000
      BLESTA_API_URL: ${BLESTA_API_URL:-}
      BLESTA_API_USER: ${BLESTA_API_USER:-}
      BLESTA_API_KEY: ${BLESTA_API_KEY:-}
      OS_AUTH_URL: ${OS_AUTH_URL:-}
      OS_USERNAME: ${OS_USERNAME:-}
      OS_PASSWORD: ${OS_PASSWORD:-}
      OS_PROJECT_NAME: ${OS_PROJECT_NAME:-admin}
      OS_USER_DOMAIN_NAME: ${OS_USER_DOMAIN_NAME:-Default}
      OS_PROJECT_DOMAIN_NAME: ${OS_PROJECT_DOMAIN_NAME:-Default}
      OS_REGION_NAME: ${OS_REGION_NAME:-RegionOne}
    networks:
      - dokploy-network
    depends_on:
      - blesta

volumes:
  blesta-data: {}
  mariadb-data: {}

networks:
  dokploy-network:
    external: true
